baseURL = "https://ugeneunipro.github.io/docs/"
title = "UGENE Documentation"
theme = "docsy"
languageCode = "en-us"

enableRobotsTXT = true
canonifyURLs = true

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false

[params]
  copyright = "2025"
  offlineSearch = true
  ui.defaultTheme = "light"
  ui.footerAbout = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/docs/"
    weight = 1
